- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: spring-boot-admin
    name: spring-boot-admin
  spec:
    replicas: 1
    selector:
      app: spring-boot-admin
      deploymentconfig: spring-boot-admin
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: spring-boot-admin
          deploymentconfig: spring-boot-admin
      spec:
        serviceAccountName: spring-boot-admin-sa
        containers:
          name: spring-boot-admin
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
        terminationGracePeriodSeconds: 30
    triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
            - spring-boot-admin
          from:
            kind: ImageStreamTag
            name: jcore-spring-boot-admin:latest
            namespace: demo
        type: ImageChange
      - type: ConfigChange