- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: spring-boot-admin
    name: spring-boot-admin
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: spring-boot-admin-webservice
      weight: 100

- kind: Service
  apiVersion: v1
  metadata:
    name: spring-boot-admin-webservice
    labels:
      app: spring-boot-admin
  spec:
    ports:
      - name: 8080-tcp
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      app: spring-boot-admin

- kind: Service
  apiVersion: v1
  metadata:
    name: spring-boot-admin-actuator
    labels:
      app: spring-boot-admin
      type: actuator
  spec:
    ports:
      - name: 8081-tcp
        protocol: TCP
        port: 8081
        targetPort: 8081
    selector:
      app: spring-boot-admin